spring:
  # jpa.show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://rm-bp1k6dy03e1nj07q8o.mysql.rds.aliyuncs.com:3306/hsfdkf?useSSL=false
    username: hsfd
    password: hsfd@2018

#华东院部署
#spring:
#  # jpa.show-sql: true
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    jdbc-url: jdbc:mysql://10.215.142.129:3306/hsfdkf?useSSL=false
#    username: hsfd
#    password: hsFD@2018